### ISSUE TITLE
Behaviour on mobile

### ISSUE THREAD

**Issue by Enngage** [cormacrelf/angular-skyhook#12]
Hi! Thanks for the awesome library, really like it and we would likely rewrite our code to use this rather than the unmaintained dragula. I thing that I would like to see is better mobile support as it currently logs errors in console and doesn't behave right. Having some custom handler would be a nice touch too.

**Comment by cormacrelf** [comment]
Have you looked at the touch backend or the multi backend? The neat thing about this and react-dnd is you can swap out the part that attaches event listeners for whatever you like. This repo doesn’t even contain any event handler code, so you can do unit testing isolated from that as well.

Follow https://cormacrelf.github.io/angular-skyhook/angular-skyhook-multi-backend/

Also if you have errors... please tell me what they are!

**Comment by cormacrelf** [comment]
Absent any actual issue here, closing.
