### ISSUE TITLE
skyhook-preview not exported?

### ISSUE THREAD

**Issue by AndrewJSchoen** [cormacrelf/angular-skyhook#261]
Hi,

I am trying to set up a simple version of the kanban board, based on the example you provide. However, despite compiling, I get a javascript error: `Can't bind to 'allBackends' since it isn't a known property of 'skyhook-preview'.` coming from the `kanban-board` component. Do you think you may know what is happening here? Any assistance would be greatly appreciated!

**Comment by cormacrelf** [comment]
Did you install the multi backend and add import it into your app module?

**Comment by AndrewJSchoen** [comment]
Thanks for the quick reply. Here are the relevant parts of my `app.module.ts`:

```
import { SkyhookDndModule } from "@angular-skyhook/core";
import { createDefaultMultiBackend } from '@angular-skyhook/multi-backend';
import { SkyhookSortableModule } from '@angular-skyhook/sortable';
```
...
```
@NgModule({
  declarations: [
    AppComponent,
    ContainerComponent,
    KanbanExternalComponent,
    TrashCanComponent,
    KanbanBoardComponent,
    KanbanCardComponent,
    KanbanListComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    SkyhookDndModule,
    SkyhookSortableModule,
    SkyhookDndModule.forRoot({ backendFactory: createDefaultMultiBackend })
  ],
  providers: [
  ],
  bootstrap: [AppComponent]
})
```

**Comment by cormacrelf** [comment]
Yeah, you need the multi backend module as well. It's not documented, which is my bad.

https://github.com/cormacrelf/angular-skyhook/blob/master/packages/examples/src/app/sortable/kanban/module.ts#L35

**Comment by cormacrelf** [comment]
(Also, in your case, you have listed SkyhookDndModule twice. Keep the second one with `forRoot`.)
