### ISSUE TITLE
Marry Kanban reducer with HttpClient

### ISSUE THREAD

**Issue by sneakypython1989** [cormacrelf/angular-skyhook#290]
Hi,

Could you please give me a hint, for how and where shall Http post requests ought to be made at your Kanban Board example, more specifically, how should initialState variable be populated by a database post/get request.

The obvious candidates are lists.ts and store.ts. BUT... The problem is that you chose to use export functions instead of Angular Services that come with DI. 

If you have time, please help.

**Comment by cormacrelf** [comment]
It’s just plain ngrx/store. Create an action to replace the board, fire it when the http request comes back. I have used ngrx/effects for this before, and it was okay. If this doesn’t seem easy to you, then read up a bit more on ngrx/store, they have much better documentation than I could ever put in a comment.

**Comment by cormacrelf** [comment]
You don’t have to use ngrx/store, but being an idiomatic ngrx codebase, it would require rewriting most of the kanban example to remove all traces. It’s a big architectural choice. I would note as I have elsewhere that programming these things is easier with some sort of immutable helper, whether or not you use ngrx — Immer comes to mind.

**Comment by sneakypython1989** [comment]
Thank you for your quick and informative response, I will have a look at ngrx/store & Immer, and try make my own custom action for that.
