### ISSUE TITLE
Changing style of preview while dragging

### ISSUE THREAD

**Issue by milwilso** [cormacrelf/angular-skyhook#356]
I am looking to change the style of a preview based on it's location to have the following behavior:

- When hovering over one of the green zones apply one opacity level
- When hovering in the middle white zone apply a different opacity level

I can get this behavior when hovering of the element that the original drag source is attached too (the dragging elements original location) but not when hovering over a different instance of the same element (each instance has a drag source defined).

Is there a way this can be done?

![drop-zones](https://user-images.githubusercontent.com/50843976/58043883-0249fe00-7b04-11e9-89cb-57bac2585d48.png)

**Comment by cormacrelf** [comment]
Yes? Any drop target can do anything it likes in its hover method. Including changing a boolean on the item being dragged, for example. That’s how spill targets work in sortable, for example. I don’t see what drag sources and other isDragging==true drag sources have to do with it.

**Comment by milwilso** [comment]
My bad it's probably more a drop target thing not drag source. I've updated the example image to more accurately show the layout.  Each of the 4 are difference instances of the same component and have both a drag source and a drop target. If an element is dropped on one of the green areas it is moved to be on that side of the element the cursor is over when dropped. If it is hovering over a green area but not dropped the opacity should change.

I tried doing something similar to what you described with a bool that gets updated in the hover of the drop target being hovered over. When debugging I can see the bool in the instance of the element being hovered over gets updated to the value I expect based on where the cursor is in that elements hover method. The problem seems to be the preview is only looking at the bool on the element being dragged not the bool of the drop target currently being hovered over.

![drop-zones](https://user-images.githubusercontent.com/50843976/58045815-3542c080-7b09-11e9-83a0-5f04d35c77b8.png)

**Comment by cormacrelf** [comment]
The drop targets should be modifying the bool in their hover method. Still has nothing to do with whether or not the target is the same as the drag source.

**Comment by cormacrelf** [comment]
You are rendering your own preview right?

**Comment by milwilso** [comment]
Here is some sample code of what each instance looks like. Each drop target is modifying the bool of their instance in their hover method. 

The behavior I am seeing with this setup is the preview looks like it is only reading the bool from the instance being dragged as the updated style is only applied when the bool of that instance is changed not when the bool of the drop target currently being hover over is changed .

panel-group.component.ts:
```typescript
public panelGroup: panel[];
```

panel-group.component.html:
```html
<ng-container *ngFor="let panel of panelGroup; let i= index>
   <panel [id]="i"></panel>
</ng-container>
```

panel.component.ts
```typescript
// The ID of this panel
@Input() public id: number;
// The ID of the panel being dragged
public draggingId: number
// Flag indicating the panel being dragged if hovering over a defined drop zone
public canDrag: boolean;

beginDrag:
   this.draggingId = this.id;
   ...

engDrag:
   this.draggingId = undefined;
   ...

hover:
   ...
   this.canDrop = (direction !== Direction.None) ? true : false;
   ...
```

panel.component.html:
```html
<skyhook-preview>
   <ng-template let-type>
      <ng-container [ngSwitch]="type">
         <ng-container *ngSwitchCase="'ITEM'">
            <div *ngIf="draggingDockPanelId === id" [style.opacity]="canDrop ? 0.4 : 1">
               <panel-header></panel-header>
               <ng-container *ngIf="draggingId ">
                  <ng-container *ngTemplateOutlet="panelContent"></ng-container>        
               </ng-container>
            </div>
         </ng-container>
      </ng-container>
   </ng-template>
</skyhook-preview>
<div class="panel__container" [dropTarget]="dropTarget">
   <panel-header [dragSource]="dragSource"></panel-header>
   <ng-container>
      <ng-container *ngTemplateOutlet="panelContent"></ng-container>        
   </ng-container>
</div>
<ng-template #panelContent>
   <ng-content></ng-content>
</ng-template>
```

**Comment by cormacrelf** [comment]
I’m not sure why you thought that would work. That’s a local variable on a component, mate. Of course it doesn’t affect the other component instances.

My suggestion was to set a boolean on the item.

```typescript
{
  hover: (monitor) => {
    let item = monitor.getItem();
    item.whatever = true;
  }
}
```

And then get the item in the preview. There are lots of examples of that.

**Comment by milwilso** [comment]
That's what I originally had tried using the monitor to "share" the boolean. I would still need to be set the value from the monitor to a local variable for the preview to see right? Or is there a way to access the value from the monitor in the preview that I didn't see in the example?

**Comment by cormacrelf** [comment]
> Or is there a way to access the value from the monitor in the preview that I didn't see in the example?

Not from the monitor, but you can access the item. That’s how the previews can render the same, dynamic thing that was picked up. Every example of previews does this. Look again.

**Comment by milwilso** [comment]
Oh I see `let-item="item"` gets the values from `monitor.getItem()`

**Comment by milwilso** [comment]
I wasn't connecting "item" with that item. Thanks for your help!

**Comment by cormacrelf** [comment]
Glad I could help. When you’re done, kindly close the issue.

**Comment by milwilso** [comment]
Will do, running a final build to verify.
