### ISSUE TITLE
Can the cursor be set to the default HTML5 cursor?

### ISSUE THREAD

**Issue by milwilso** [cormacrelf/angular-skyhook#359]
Is it possible to change the cursor while dragging to the default HTML cursor (`cursor: default`)? In the docs it calls out an interface to select the copy, move, link, or none cursors but not the default.

**Comment by cormacrelf** [comment]
In general, this is more a question for the react-dnd repo. This one doesn’t control cursors at all, it just has to document the APIs it exposes.

For example here: https://github.com/react-dnd/react-dnd/issues/325
