### ISSUE TITLE
SortableSpec canDrag not used

### ISSUE THREAD

**Issue by elongberg** [cormacrelf/angular-skyhook#360]
In using the `sortable` package, I notice the `canDrag` function of `SortableSpec` appears to do nothing (it never gets called when actually trying it out in a `<skyhook-sortable-list>`, and after looking at the package code I believe it's not actually being used).

Is there another method that should be used for this functionality (i.e. being able to specify if a given item in a list can be dragged or not), or is this just an oversight?

**Comment by cormacrelf** [comment]
It’s an oversight. This code should clearly implement canDrag. Thanks for reporting.

https://github.com/cormacrelf/angular-skyhook/blob/5326af47c80e306b473eb8858d0a79f0187e7fcc/packages/sortable/src/directives/render.directive.ts#L88

**Comment by zebrada** [comment]
Did not see this bug report until then but I was just having the same problem. 

Happy to see that it is tracked already. 

Is there a workaround ? It appears to me that DragSourceSpec  can't be modified once it has been created.

**Comment by cormacrelf** [comment]
If there were a workaround I would have mentioned it. Just be patient and I will get to it.

**Comment by zebrada** [comment]
It wasn't my intention to rush you in any way.

Thank you for your commitment.
