### ISSUE TITLE
bug: type error in `@angular-skyhook/multi-backend` 1.2.1

### ISSUE THREAD

**Issue by thefliik** [cormacrelf/angular-skyhook#431]
Upgrading to `@angular-skyhook/multi-backend` 1.2.1 triggers the following type error during Angular compilation:

```
ERROR in ../../node_modules/react-dnd-touch-backend/dist/Touch.d.ts(63,103): error TS2536: Type 'EventName[K]' cannot be used to index type 'WindowEventMap'.
    ../../node_modules/react-dnd-touch-backend/dist/Touch.d.ts(64,106): error TS2536: Type 'EventName[K]' cannot be used to index type 'WindowEventMap'.
```

I don't see this error in version 1.1.1. Given that version 1.1.1 still seems to work in Angular v8, downgrading is a work-around. It's possible this type error is only raised in ts `strict` mode.

My `tsconfig.json` file looks like:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": ".",
    "sourceMap": true,
    "declaration": false,
    "target": "es2015",
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strict": true,
    "strictPropertyInitialization": false,
    "allowSyntheticDefaultImports": true,
    "downlevelIteration": true,
    "removeComments": true,
    "importHelpers": true,
    "paths": {
      "@local/*": ["libs/*"],
      "@local-patches/*": ["patched-3rd-party-libs/*"],
      "lodash/*": ["node_modules/@types/lodash-es/*"]
    },
    "lib": ["dom", "esnext"],
    "typeRoots": ["node_modules/@types", "typings"]
  },
  "exclude": ["node_modules", "tmp"]
}
```

**Comment by thefliik** [comment]
It's possible that upgrading to react-dnd v9, as [mentioned in a comment](https://github.com/cormacrelf/angular-skyhook/issues/430#issuecomment-511662507) to #430, will also address this issue.

**Comment by cormacrelf** [comment]
Sorry for the wait. Latest (1.3.1) raises the minimum dnd-core version to 9. Please check if this is resolved.

**Comment by thefliik** [comment]
> Sorry for the wait

No worries! Upgrading to version 9 does fix this issue. However, it also created a new issue:

In my app module I've been importing `SkyhookDndModule` like so (working in `1.1.1`)

```ts
SkyhookDndModule.forRoot({ backendFactory: createDefaultMultiBackend }),
```

In version `1.3.0` the following type error is raised:

```bash
Argument of type '{ backendFactory: BackendFactory; }' is not assignable to parameter of type 'BackendInput | BackendFactoryInput'.
  Type '{ backendFactory: BackendFactory; }' is not assignable to type 'BackendFactoryInput'.
    Types of property 'backendFactory' are incompatible.
      Type 'BackendFactory' is not assignable to type '() => BackendFactory'.
```

This can be fixed by creating an exported function which returns `createDefaultMultiBackend`:

```ts
export function backendFactory() {
  return createDefaultMultiBackend;
});

SkyhookDndModule.forRoot({ backendFactory });
```

I think the real fix is updating `createDefaultMultiBackend` to have the type `() => BackendFactory`.

**Comment by cormacrelf** [comment]
Did you also update dnd-multi-backend?

**Comment by thefliik** [comment]
I did

**Comment by thefliik** [comment]
Wait, I read that as "Did you also update @angular-skyhook/multi-backend?"

**Comment by cormacrelf** [comment]
Your PR is correct. I also tried to update to dnd-multi-backend v4.0.0 as it's meant to be easier to use with dnd-core v9, but apparently that breaks all dragging, so I will stick with 3.2.1 for now.

**Comment by cormacrelf** [comment]
`@angular-skyhook/multi-backend` 1.3.2 released
