### ISSUE TITLE
Running ng build with optimization set to true breaks this library

### ISSUE THREAD

**Issue by i3anaan** [cormacrelf/angular-skyhook#442]
## Problem
Apperantly setting `"optimzation": true` in angular.json causes an app that functions normally without optimization (i.e. debug/development) to break with optimization (production mode).

Since [Angular's stance on the matter](https://github.com/angular/angular-cli/issues/11439) is pretty much that the library should fix it, I'm posting an issue for it here.

## Steps to reproduce:
- Have an angular project using skyhook
- build using `"optimzation": true` (i.e. `ng build --prod`)
- Try and use skyhook by dragging an object
- Experience it not working

### Error in console:
```
Uncaught Invariant Violation: Cannot call endDrag while not dragging.
    at QLaP.e.exports (https://url/main.2884ec44a6f193632cc5.js:1:238563)
    at https://url/main.2884ec44a6f193632cc5.js:1:1088445
    at uF.<anonymous> (https://url/main.2884ec44a6f193632cc5.js:1:1088504)
    at Object.i.<computed> [as beginDrag] (https://url/main.2884ec44a6f193632cc5.js:1:1088678)
    at handleTopDragStart (https://url/main.2884ec44a6f193632cc5.js:1:1255778)
    at t.invokeTask (https://url/polyfills.c67528456ba5ac04556c.js:1:8753)
    at Object.onInvokeTask (https://url/polyfills.c67528456ba5ac04556c.js:1:5730)
    at t.invokeTask (https://url/polyfills.c67528456ba5ac04556c.js:1:8674)
    at e.runTask (https://url/polyfills.c67528456ba5ac04556c.js:1:3935)
    at e.invokeTask [as invoke] (https://url/polyfills.c67528456ba5ac04556c.js:1:9836)
```

### Versions
Angular cli `7.2.2`
Skyhook `1.2.1`

## Expected result
App works the same with optimization enabled or disabled.

### Workaround
Disable optimization by setting `"optimization": false` in `angular.json`

# Request
Make this library work with optimization set to true.

**Comment by cormacrelf** [comment]
This library doesn't have any side-effecting getters. It has a bunch of getters, but they are pure. At least, I have ripgrepped the codebase pretty hard and examined the ones it has. If you can find one yourself, let me know.

If it's a getter problem, it's either upstream (`dnd-core`) or in your code. My guess from your stack trace is the latter (it has `beginDrag` a few frames back).

It's not necessarily a getter problem, though. I'll think about what else it could be.

**Comment by i3anaan** [comment]
Hey, thank you for the quick response!

I checked our code, and there is not a single place where we call `endDrag` ourselves, thus making me think it cannot be our fault.
If this assumption is wrong and it could still be our fault please say so, then I will do another more thorough examination.

**Comment by i3anaan** [comment]
I also did a quick search in dnd-core, and found this issue that is atleast somewhat similar: https://github.com/react-dnd/react-dnd/issues/1049

Will have another, better, look tomorrow.

**Comment by i3anaan** [comment]
So this morning I did some searching around and I found more issues on `dnd-core` related to minimization. So if you agree that they should fix this we can close this issue here, and I'll make a new one over there.

**Comment by i3anaan** [comment]
Wew, after what looked like it was turning into a very big headache this morning turned out pretty great, I found a workaround!

Basically it boils down to not using UglifyJS as minimizer in webpack, as that somehow breaks something somewhere related to using drag and drop (in skyhook). To achieve this I made a sort of hack for the `@angular-devkit/build-angular` package using the `patch-package` package.

`patch-package` was used to generate a patch for the `@angular-devkit/build-angular` package ([I used this site as a how-to](https://blog.callstack.io/say-goodbye-to-old-fashioned-forks-thanks-to-the-patch-package-3c63a62eea1c)). I attached the patch file's content at the bottom. Then I set up a `prepare` hook in the `package.json` like this:

```
  "scripts": {
    "prepare": "patch-package",
    ...
    }
```

And it works! :D


---
Patch file used:

```
diff --git a/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js b/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js
index 99903a9..717f3bb 100644
--- a/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js
+++ b/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js
@@ -22,7 +22,7 @@ const find_up_1 = require("../../utilities/find-up");
 const utils_2 = require("./utils");
 const ProgressPlugin = require('webpack/lib/ProgressPlugin');
 const CircularDependencyPlugin = require('circular-dependency-plugin');
-const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
+const TerserPlugin = require('terser-webpack-plugin');
 const StatsPlugin = require('stats-webpack-plugin');
 /**
  * Enumerate loaders and their dependencies from this file to let the dependency validator
@@ -267,12 +267,7 @@ function getCommonConfig(wco) {
                     // component styles retain their original file name
                     test: (file) => /\.(?:css|scss|sass|less|styl)$/.test(file),
                 }),
-                new UglifyJSPlugin({
-                    sourceMap: buildOptions.sourceMap,
-                    parallel: true,
-                    cache: true,
-                    uglifyOptions,
-                }),
+                new TerserPlugin(),
             ],
         },
         plugins: extraPlugins,
```

**Comment by cormacrelf** [comment]
You should probably run your (unfixed) code in a debugger with pausing on exceptions enabled (and source maps). Then you’ll know where it actually is.

**Comment by cormacrelf** [comment]
Closing because the examples still work with `--prod` so it’s not this library’s problem.
