### ISSUE TITLE
Simple sortable freeze on drop

### ISSUE THREAD

**Issue by directcuteo** [cormacrelf/angular-skyhook#468]
Hi!

If you check this simple sortable example link 

https://cormacrelf.github.io/angular-skyhook/examples/index.html#/sortable/simple-kanban

and you try do drop items fast from one list to another, they sometimes freeze in the air!

I have implemented the example in my code also and it does the same. Can be this fixed?

Thank you!

**Comment by cormacrelf** [comment]
What browser/OS are you experiencing the issue on? There is a firefox bug that sounds like what you describe, and that I can reproduce, that has recently regressed. More details at https://github.com/react-dnd/react-dnd/issues/1000

**Comment by directcuteo** [comment]
I am experiencing te issue on Chrome v. 77, Windows 10.

**Comment by cormacrelf** [comment]
Chrome 77 has a bug. Could be it. https://bugs.chromium.org/p/chromium/issues/detail?id=1005747

**Comment by cormacrelf** [comment]
Also ref https://github.com/react-dnd/react-dnd/issues/1534 where people are tracking Chrome patches. Not however that the angular-skyhook demo page is not running in an iframe, so I'm not entirely convinced. Would be good to confirm this goes away when Chrome is fixed.
