### ISSUE TITLE
wrong offset in preview in chrome with win10 scaling on

### ISSUE THREAD

**Issue by mikanyg** [cormacrelf/angular-skyhook#504]
I am experincing issues with the html5backend in Chrome that I only see on my laptop with a 4K display. The preview image is being rendered with an offset very close to the top left corner of the dragged image no matter where the offset was initially when drag started. I have tracked this down to the windows scaling which is on by default when using 4K monitors. When turning scaling off the behaviour in chrome is as expected, that the offset of the preview image is the same as where the cursor was initially when drag started.

In firefox everything works as expected with or without scaling turned on.

I am unsure if this is the proper place to report this, but had to start somewhere.

**Comment by cormacrelf** [comment]
Find the react-dnd example with image previews. If it has the same issue, then close this and file there.

**Comment by mikanyg** [comment]
Thx for the tip, got an easy repro on this example https://react-dnd.github.io/react-dnd/examples/customize/handles-and-previews. I will close here and open in react-dnd.

**Comment by mikanyg** [comment]
Issue located here https://github.com/react-dnd/react-dnd/issues/1583

**Comment by krishnaraj1988** [comment]
is this issue not fixed yet? because i still see this here https://react-dnd.github.io/react-dnd/examples/customize/handles-and-previews
