### ISSUE TITLE
Single backends do not work in 1.3.0+

### ISSUE THREAD

**Issue by generesque** [cormacrelf/angular-skyhook#505]
I tried integrating skyhook into a project and ran into some issues. As a sanity check, I took the sample code from the documentation (https://cormacrelf.github.io/angular-skyhook/additional-documentation/guide/2.-connecting-to-dom.html) and tried to just run it. I expect to see something on the console when I drop the source on the target, but I don't see anything. Stackblitz: https://stackblitz.com/edit/angular-zkhsie

I've tried angular 7 and 8, skyhook 1.2 and 1.3, Chrome and Firefox. Nothing works. I'm assuming I'm just missing something obvious, but figuring out what that is and updating the documentation might be helpful.

**Comment by cormacrelf** [comment]
Yep, you're running an ancient `react-dnd-html5-backend`. You don't get peerDependencies warnings on StackBlitz. Upgrade it to v9 and it works.

**Comment by generesque** [comment]
I was actually just testing different package combinations to see if I could find something that works. The stackblitz is back to what my project is:

    "@angular-skyhook/core": "^1.3.0",
    "react-dnd-html5-backend": "^9.4.0",

This combination does not work at all. The only working combination I could find was indeed ancient:
    "@angular-skyhook/core": "^1.0.11",
    "react-dnd-html5-backend": "^5.0.1",

Maybe there was a recent change to react-dnd-html5-backend that broke something?

**Comment by cormacrelf** [comment]
It's actually very weird, I got the StackBlitz to work exactly once and then it stopped.

**Comment by generesque** [comment]
Ok, I've done some more testing, and it seems that `@angular-skyhook/core 1.3.0` or greater does not work at all with `react-dnd-html5-backend 9.0.0` or greater. `@angular-skyhook/core 1.2.1` works with all `react-dnd-html5-backend 9.x.x` versions.

**Comment by generesque** [comment]
Works: https://stackblitz.com/edit/angular-ljqvgb?file=package.json
Broken: https://stackblitz.com/edit/angular-h32cv8?file=package.json

I am unblocked at least because I can just downgrade to 1.2.1. Let me know if there's anything else I can do to help debug

**Comment by cormacrelf** [comment]
I figured it out. `dnd-core` has, at some point, changed the way global context is provided. It used to be that `{ window: window }` worked, but now apparently you need to pass just a plain `window` object. I cannot find this in any release notes, so I don't know when it broke. It also explains why the examples app with the multi-backend was fine -- it was relying on dnd-multi-backend to provide the context.

**Comment by cormacrelf** [comment]
fixed in 1.3.3 https://stackblitz.com/edit/angular-syurf7

**Comment by generesque** [comment]
I can confirm my use case is fixed as well. Thank you so much for the speedy resolution.
