### ISSUE TITLE
Is there an npm package for angular-skyhook-card-list?

### ISSUE THREAD

**Issue by Digister** [cormacrelf/angular-skyhook#78]
Hi, I am trying to get sortable/simple example to run, but unfortunately I can not find an package for angular-skyhook-card-list. Also I was able to successfully install angular-skyhook and angular-skyhook-multi-backend via npm. I am not sure how to get the missing package. Can you help me here?
Thanks.

**Comment by cormacrelf** [comment]
I think I have noted it clearly at least four times in the docs. No, it is not released because I have not nailed down the API. See #69, I might do some betas if you want to try it in the real world. You may still use the Basic Sortable pattern in the examples.
