### ISSUE TITLE
don't work with iframe

### ISSUE THREAD

**Issue by haxiha** [cormacrelf/angular-skyhook#9]
hi, how can i drop a item Outside to Inside iframe ? i dragged without effect.

**Comment by cormacrelf** [comment]
See https://github.com/react-dnd/react-dnd/issues/241

Note that dnd-core does not claim to support iframes. There is a solution I haven’t tested at the bottom of that thread using the DragDropManager.getBackend() function. You could replicate it by injecting `@Inject(DRAG_DROP_MANAGER) manager: DragDropManager` into your component, and copying those two addEventListener lines into the equivalent Angular lifecycle hooks. Good luck.
